INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('6','CH616049','Mobile Technology','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('6','CH616050','Pengemb. Aplikasi Berbasis Web','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('6','CH616051','Audit IT','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('6','CH616052','Data Warehouse','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('6','CH616053','Sistem Temu Kembali Informasi','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('6','CH616056','Digital Forensik','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616060','E-Government','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616063','Sistem Informasi Akuntansi','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616054','Sistem Informasi Geografis','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616055','Manajemen Layanan TI','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616057','Socio Informatics','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616058','Integrasi Aplikasi Korporasi','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616059','Bisnis Cerdas','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616061','Teknik Peramalan','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616062','Sistem Pendukung Keputusan','3','1','Program Studi');
INSERT INTO tabel_5_1_3(smt, kode_mk, nama_mk, sks, tugas, unit) VALUES('7','CH616064','Data Mining','3','1','Program Studi');
