INSERT INTO tabel_7_1_4(karya, url) VALUES('Paten NUI Menggunakan Kinect FIS-TSK','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('PROTOTIPE SISTEM INFORMASI DETEKSI MASJID TERDEKAT MENGGUNAKAN PETA DIGITAL BERBASIS MULTI-PLATFORM DEVICE (MOBILE AND WEB) SEBAGAI PENDUKUNG PELAKSANAAN BADAH SHOLAT TEPAT WAKTU','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Hak Cipta Atas Judul Ciptaan : "PERANCANGAN ROBOTIK BOAT PEMANTAUAN Tanggal dan tempat diumumkan SEDIMEN SUNGAI SEBAGAI DATA ANALISIS KEBIJAKAN PENGELOLAAN AIR DAS BRANTAS" dari Kemnterian Hukum dan HAM','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Sertifikat HAKI atas "Aplikasi Literasi dan Buku Berjenjang" di Laboratorium Fakultas Tarbiyah','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Sertifikat HAKI atas Makalah " Islamic Green Computing"','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Buku KRIPTOGRAFI & KEAMANAN KOMPUTER : “Prinsip,Teoritis Dan Praktis" ','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Teknologi Live Streaming: Media Penunjang Dakwah Dan Kegiatan Belajar Mengajar Untuk Mendukung Cyber University','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Sistem Pendukung Keputusan Untuk Proses Kelulusan Dan Evaluasi Kinerja Akademik Mahasiswa Menggunakan Teknik Data Mining','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Penerapan Data Mining Untuk Evaluasi Kinerja Akademik Mahasiswa Menggunakan Algoritma Naive Bayes Classifier','');
INSERT INTO tabel_7_1_4(karya, url) VALUES('Pedoman KKN Literasi dengan Pendekatan ABCD','');
