INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Achmad Teguh Wibowo','Panitia SPAN UM PTKIN 2016','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Achmad Teguh Wibowo','Panitia SPAN UM PTKIN 2017','2017','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Achmad Teguh Wibowo','Presenter BEST ICON 2018','2018','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ahmad Yusuf, M.Kom.','Panitia SPAN UM PTKIN 2016','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ahmad Yusuf, M.Kom.','Panitia SPAN UM PTKIN 2017','2017','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ahmad Yusuf, M.Kom.','Panitia SPAN UM PTKIN 2018','2018','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ahmad Yusuf, M.Kom.','Kajian Integrasi Sains dan Teknologi dengan Keislaman','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ahmad Yusuf, M.Kom.','Dosen Terbaik Prodi Sistem Informasi','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ahmad Yusuf, M.Kom.','Dosen Terbaik Prodi Sistem Informasi','2017','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Anang Kunaefi, M.Kom','Program Penunjang 5000 Doktor','2017','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Bayu Adhi Nugroho','Menulis artikel di muat Prosiding ICNERE-ECCIS 2016','2016','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Bayu Adhi Nugroho','IIFAS 2017 - International Indonesian Forum for Asian Studies','2017','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Bayu Adhi Nugroho','Kursus Intensif Bahasa Asing','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Bayu Adhi Nugroho','Program Penunjang 5000 Doktor','2017','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Dwi Rolliawati','Ketua Konsorsum keilmuan Teknologi','2015','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Dwi Rolliawati','Review Redesign Curiculum KKNI','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Dwi Rolliawati','Moderator BEST ICON 2018','2018','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Faris Mushlihul Amin, M.Kom','Pembina PC PMII Probolinggo','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Faris Mushlihul Amin, M.Kom','Pengurus Wilayah GP Ansor Jawa Timur','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Faris Mushlihul Amin, M.Kom','Wakil Ketua Gerakan Pemuda Jawa Timur','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Faris Mushlihul Amin, M.Kom','Presenter BEST ICON 2018','2018','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Faris Mushlihul Amin, M.Kom','JPPR Jawa Timur','2018','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ilham M.Kom','Hibah Bersaing 2013-2015 DIKTI','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ilham M.Kom','Pemateri dalam acara Pelatihan Peningkatan Kompetensi Mhs Prodi SI di Lab Komputer UIN Sunan Ampel Sby','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Ilham, M.Kom','Seminar rekayasa perangkat lunak deteksi dini kecenderungan gangguan kesehatan masyarakat tertinggal dan pesisir dengan bayesian network','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Indri Sudanawati Rozas, M.Kom','reviewer jurnal nasional JTIIK Universitas Brawijaya','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Khalid, M.Kom','Kursus : English Language Training (Pre-Intermediate 1) di IALF Surabaya','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Khalid, M.Kom','Presenter ICON QUHAS di Bandung','2018','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','reviewer jurnal Register UNIPDU','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Tim editorial jurnal NJCA(Nusantara Journal of Computer and Applications)','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Pemakalah dalam konferensi Internasional (ber ISSN) ''International Conference on Record and Library - Reinventing Information Professionals''','2015','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Pemakalah dalam konferensi Internasional (ber ISSN) ''International Conference on Record and Library - Transforming Information in the New Media''','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Pemakalan dalam konferensi Internasional ''The 16th Annual International Conference on Islamic Studies - The Contribution of Indonesian Islam to The World Civilization''','2016','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Menerbitkan karya ilmiah Prototype Sistem Informasi Manajemen Keselamatan dan Kesehatan Kerja E-K3 Menggunakan Peta Digital Berbasis Web dan Mobile','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Memberi pelatihan kepada SDIT Al Mukminun Ngrambe, Ngawi, Jawa Timur','2015','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Memberi pelatihan kepada SMA Darul Mukhlasin','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Memberi pelatihan kepada Ma''had Aly As''adiah, Sengkang, Sulawesi Selatan','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch Yasin, S.Kom., M.Kom., MBA','Memberi pelatihan kepada SMK Bilingual Al-Yasini','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Muhammad Andik Izzuddin, MT','Panitia SPAN UM PTKIN 2016','2016','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Muhammad Andik Izzuddin, MT','Panitia SPAN UM PTKIN 2017','2017','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Muhammad Andik Izzuddin, MT','Kursus : English Language Training (Pre-Intermediate 1) di IALF Surabaya','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Muhammad Andik Izzuddin, MT','Presenter BEST ICON 2018','2018','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Bidang Pengembangan SDM LPTNU PW Jatim','2015','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Editor Jurnal Systemic','2015','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Redaktur Jurnal Systemic','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Workshop "Optimalisasi potensi psikologi siswa berbasis manajemen data"','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Pelatihan Sistem Informasi Sekolah dengan tema "Penataan Manajemen Sekolah Berbasis Teknologi dan Kesehatan"','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Pelatihan Sistem Informasi Sekolah dengan tema "Peningkatan SDM dan Penggunaan Teknologi"','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Workshop "Writing Interest Upgrading: Strategi Publikasi Karya Ilmiah"','2017','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Kursus: General English for adults level 2 di IALF Surabaya','2015','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Presenter BEST ICON 2018','2018','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Yusuf Amrozim MMT','Dosen Terbaik Prodi Sistem Informasi','2016','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Yusuf Amrozi, MMT','Penerimaan Bantuan Penelitian LPPM UINSA','2015','Lokal');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Mujib Ridwan, M.T','Pemateri Seminar Nasional: ASWAJA dan Polemik Kemanusiaan di Auditorium MA Nurul Jadid','2019','Nasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Moch. Yasin','presenter di International Conference on Record Library','2019','Internasional');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Indri Sudanawati Rozas, M.Kom','Penyuluhan gadget warning system di SMP 62','2019','');
INSERT INTO tabel_4_5_4(nama_dosen, prestasi, tahun, tingkat) VALUES('Indri Sudanawati Rozas, M.Kom','presenter di International Conference on Social Science','2019','Internasional');
