<script src="<?=base_url();?>assets/js/jquery.min.js"></script>
<script src="<?=base_url();?>assets/bootstrap/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="<?=base_url();?>assets/js/Bootstrap-DataTables.js"></script>
<script src="<?=base_url();?>assets/js/datatables.min.js"></script>
<script src="<?=base_url();?>assets/js/functions.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
<script src="<?=base_url();?>assets/js/numeral.js"></script>
<script src="<?=base_url();?>assets/js/theme.js"></script>