<p>Peraturan-peraturan yang menjadi rujukan dalam menjamin pelaksanaan Kebebasan Akademik, Kebebasan Mimbar Akademik, dan Otonomi Keilmuan Dosen UIN Sunan Ampel Surabaya yaitu:</p>
<ol>
	<li>Undang-undang Republik Indonesia Nomor 12 Tahun 2012 Tentang Pendidikan Tinggi Pasal 8, Pasal 9 dan Pasal 10.</li>
	<li>Peraturan Menteri Agama Republik Indonesia Peraturan Menteri Agama Republik Indonesia Nomor 56 Tahun 2015 Tentang Statuta Universitas Islam Negeri Sunan Ampel Surabaya Pasal 11.</li>
	<li>Surat Keputusan Rektor Nomor 283 Tahun 2017 Tentang Etika, Otonomi Keilmuan, dan Kebebasan Mimbar Akademik Dosen</li>
</ol>
<p>Undang-undang Nomor 12 Tahun 2012 Pasal 8 Ayat 3 menetapkan bahwa pelaksanaan kebebasan akademik, kebebasan mimbar akademik, dan otonomi keilmuan di Perguruan Tinggi merupakan tanggung jawab pribadi sivitas akademika, yang wajib dilindungi dan difasilitasi oleh pimpinan perguruan tinggi.</p>
<p><b>Pasal 9 Ayat 1</b> menetapkan bahwa kebebasan akademik merupakan kebebasan sivitas akademika dalam Pendidikan Tinggi untuk mendalami dan mengembangkan ilmu pengetahuan dan teknologi secara bertanggung jawab melalui pelaksanaan Tridharma.</p>
<p><b>Pasal 9 Ayat 2</b> menetapkan bahwa kebebasan mimbar akademik merupakan wewenang professor dan/atau dosen yang memiliki otoritas dan wibawa ilmiah untuk menyatakan secara terbuka dan bertanggung jawab mengenai sesuatu yang berkenaan dengan rumpun ilmu dan cabang ilmunya.</p>
<p><b>Pasal 9 Ayat 3</b> menetapkan bahwa otonomi keilmuan merupakan otonomi sivitas akademika pada suatu cabang ilmu pengetahuan dan/atau teknologi dalam menemukan, mengembangkan, mengungkapkan, dan/atau mempertahankan kebenaran ilmiah menurut kaidah, metode keilmuan, dan budaya akademik.</p>
<p>Peraturan Menteri Agama Republik Indonesia Nomor 56 Tahun 2015 tentang Statuta Universitas Islam Negeri Sunan Ampel Surabaya;</p>
<p>Pada <b>Bab III Pasal 11 ayat 1</b> menetapkan Universitas menjunjung tinggi kebebasan akademik, kebebasan mimbar akademik, dan otonomi keilmuan.</p>
<p>Pada <b>Pasal 11 Ayat 2</b> ditetapkan bahwa kebebasan akademik merupakan kebebasan sivitas akademika pada Universitas untuk mendalami dan mengembangkan ilmu pengetahuan dan teknologi secara bertanggung jawab melalui pelaksanaan tridharma perguruan tinggi.</p>
<p><b>Pasal 11 Ayat 3</b> menetapkan bahwa kebebasan mimbar akademik merupakan wewenang dosen yang memiliki otoritas dan wibawa ilmiah untuk menyatakan secara terbuka dan bertanggung jawab mengenai sesuatu yang berkenaan dengan rumpun ilmu dan cabang ilmunya. Otonomi keilmuan merupakan otonomi sivitas akademika pada suatu cabang ilmu pengetahuan dan teknologi dalam menemukan, mengembangkan, mengungkapkan, dan/atau mempertahankan kebenaran ilmiah menurut kaidah, metode keilmuan, dan budaya akademik. Pimpinan Universitas wajib mengupayakan dan menjamin agar setiap anggota sivitas akademika melaksanakan kebebasan akademik dan kebebasan mimbar akademik secara bertanggung jawab sesuai dengan ketentuan peraturan perundangundangan, serta dilandasi oleh etika dan norma/kaidah keilmuan.</p>